### PR TITLE
improve example project

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@xavierlesa i tried running the sample project and made some fixes along the way. but now I'm stuck, everything seems to work, but how do i get these payload prints to show up. i tried sending messages with mosquitto_pub but nothing shows up..

**Comment by sabuhish** [comment]
and update requirements.txt as well..

**Comment by thijstriemstra** [comment]
@sabuhish there is no requirements.txt in this repository.

**Review by sabuhish — APPROVED** [review]
thank you, I  appreciate your PR!

**Comment by sabuhish** [comment]
@thijstriemstra Yeah unfortunately there is no requirements.txt. It would be great if some more examples we had here.

**Comment by sako0938** [comment]
It would also be amazing to have an example of sending a MQTT message using django channels too. It looks like the functionality is there, but I've been working for a few days trying to actually send something.

**Comment by thijstriemstra** [comment]
> thank you, I appreciate your PR!

can this be merged then?

**Pull request merged**
